version: '3'
services:
#  UserService:
#    image: user-service
#    ports:
#      - "8082:8082"
#    networks:
#      - user-mysql
#    depends_on:
#      - mysqldb-user-service
#
#  EmailService:
#    image: mail-notification-service
#    ports:
#      - "8083:8083"
#    networks:
#      - mail-notification-mysql
#    depends_on:
#      - mysqldb-mail-service


  mysqldb-user-service:
    image: mysql:8.0.18
    networks:
      - user-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=dewan@12345678
      - MYSQL_DATABASE=users_db

  mysqldb-mail-service:
    image: mysql:8.0.18
    networks:
      - mail-notification-mysql
    environment:
      - MYSQL_ROOT_PASSWORD=dewan@12345678
      - MYSQL_DATABASE=mail_notification_db

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper
    ports:
      - 2181:2181
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    # See https://rmoff.net/2018/08/02/kafka-listeners-explained/ for details
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - 9092:9092
      - 29092:29092
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1


networks:
  user-mysql:
  mail-notification-mysql: